//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeadandoPiszkozat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public int ID { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string Fuel { get; set; }
        public string MaxPassenger { get; set; }
        public string NumberOfDoors { get; set; }
        public string AvailableType { get; set; }
        public string Price { get; set; }
    }
}
